cutoff_len: 256
dataset: test_lora
dataset_dir: /home/ubuntu/LLMTrain/LLMTrain/data
do_train: true
finetuning_type: lora
gradient_accumulation_steps: 2
ignore_data_skip: true
learning_rate: 0.0005
logging_steps: 1
lora_alpha: 16
lora_rank: 8
lora_target: q_proj,v_proj
max_samples: 24
model_name_or_path: Qwen/Qwen2.5-0.5B-Instruct
num_train_epochs: 2.0
output_dir: output/test_lora_output
overwrite_cache: true
per_device_train_batch_size: 4
report_to: none
save_steps: 9999
stage: sft
template: qwen
trust_remote_code: false
